<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class City extends Authenticatable
{
	/**
     * The table associated with the model.
     *
     * @var string
     */
		protected $table = 'city';
	
	/**
     * The primary key defines in table.
     *
     * @var string
     */
		protected $primaryKey = 'city_id';
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
		protected $fillable = [
			'city_name', 'city_abbr', 'state_id', 'city_status',
		];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
		protected $hidden = [

		];
	
	/**
     * This function get the order data generated by customer 
     *
     * @return Orderdata
     */
	/*public function Orderdata() 
	{
        return $this->hasMany('App\Orders','customer_id','customer_id');
    }*/
	
	/**
     * This function get the state for the city 
     *
     * @return State
     */
	public function StateData() 
	{
        return $this->belongsTo('App\State','state_id','state_id')->where('state_status','1')->orderBy('state_name','asc');
    }
	
	/**
     * This function get the property data for state 
     *
     * @return Propertydata
     */
	public function Propertydata() 
	{
        return $this->hasMany('App\Property','property_city','city_id')->where('property_status','=','1');
    }
		
}
