<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class State extends Authenticatable
{
	/**
     * The table associated with the model.
     *
     * @var string
     */
		protected $table = 'state';
	
	/**
     * The primary key defines in table.
     *
     * @var string
     */
		protected $primaryKey = 'state_id';
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
		protected $fillable = [
			'state_name', 'state_abbr', 'state_status',
		];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
		protected $hidden = [

		];
	
	/**
     * This function get the order data generated by customer 
     *
     * @return Citydata
     */
	public function Citydata() 
	{
        return $this->hasMany('App\City','state_id','state_id')->where('city_status','=','1')->orderBy('city_name','asc');
    }
	
	/**
     * This function get the property data for state 
     *
     * @return Propertydata
     */
	public function Propertydata() 
	{
        return $this->hasMany('App\Property','property_state','state_id')->where('property_status','=','1');
    }
	
}
